# Utilise l'image de base Node.js
FROM node:20-alpine

# Crée le répertoire de travail
WORKDIR /app

# Installe les dépendances nécessaires pour Prisma et PostgreSQL
RUN apk add --no-cache libc6-compat openssl

# Copie les fichiers de dépendances et installe (couche cachée)
COPY package.json package-lock.json* ./
RUN npm ci --legacy-peer-deps

# Copie explicitement le schéma et les migrations Prisma
# Cette couche sera invalidée à chaque nouvelle migration
COPY prisma ./prisma/

# La commande par défaut qui sera exécutée
CMD ["npm", "run", "db:migrate"]
