export const COAT_COLORS: string[] = [
  "*** a determiner ***",
  "black amber silver blotched tabby",
  "black amber silver blotched tabby & blanc",
  "black amber silver mackerel tabby",
  "black amber silver mackerel tabby & blanc",
  "black amber silver spotted tabby",
  "black amber silver spotted tabby & blanc",
  "black amber smoke",
  "black amber smoke & blanc",
  "black chinchilla",
  "black chinchilla & blanc",
  "black chinchilla & blanc arlequin",
  "black golden shaded",
  "black golden shaded & blanc",
  "black golden shaded & blanc bicolore",
  "black golden shaded yx or",
  "black golden shell",
  "black golden shell yx or",
  "black silver blotched tabby",
  "black silver blotched tabby & blanc",
  "black silver blotched tabby & blanc arlequin",
  "black silver blotched tabby & blanc bicolore",
  "black silver mackerel tabby",
  "black silver mackerel tabby & blanc",
  "black silver mackerel tabby & blanc arlequin",
  "black silver mackerel tabby & blanc bicolore",
  "black silver shaded",
  "black silver shaded & blanc",
  "black silver shaded & blanc arlequin",
  "black silver shaded & blanc bicolore",
  "black silver shaded & blanc yx or",
  "black silver shaded yx or",
  "black silver spotted tabby",
  "black silver spotted tabby & blanc",
  "black silver spotted tabby & blanc arlequin",
  "black silver spotted tabby & blanc bicolore",
  "black silver tabby",
  "black silver tabby (motif marble)",
  "black silver tabby (motif spotted/rosettes)",
  "black silver tabby & blanc",
  "black silver tabby & blanc arlequin",
  "black silver tabby & blanc van",
  "black silver ticked tabby",
  "black silver ticked tabby & blanc",
  "black silver ticked tabby & blanc bicolore",
  "black smoke",
  "black smoke & blanc",
  "black smoke & blanc arlequin",
  "black smoke & blanc bicolore",
  "black smoke & blanc van",
  "black tortie",
  "black tortie & blanc",
  "black tortie & blanc arlequin",
  "black tortie & blanc bicolore",
  "black tortie & blanc van",
  "black tortie amber",
  "black tortie amber & blanc",
  "black tortie amber silver blotched tabby",
  "black tortie amber silver blotched tabby & blanc",
  "black tortie amber smoke",
  "black tortie chinchilla",
  "black tortie chinchilla yx or",
  "black tortie golden shaded",
  "black tortie golden shaded & blanc",
  "black tortie golden shaded yx or",
  "black tortie golden shell",
  "black tortie golden shell & blanc",
  "black tortie golden shell & blanc arlequin",
  "black tortie golden shell yx or",
  "black tortie silver blotched tabby",
  "black tortie silver blotched tabby & blanc",
  "black tortie silver blotched tabby & blanc arlequin",
  "black tortie silver blotched tabby & blanc bicolore",
  "black tortie silver mackerel tabby",
  "black tortie silver mackerel tabby & blanc",
  "black tortie silver mackerel tabby & blanc arlequin",
  "black tortie silver mackerel tabby & blanc bicolore",
  "black tortie silver shaded",
  "black tortie silver shaded & blanc",
  "black tortie silver shaded & blanc bicolore",
  "black tortie silver shaded yx or",
  "black tortie silver spotted tabby",
  "black tortie silver spotted tabby & blanc",
  "black tortie silver spotted tabby & blanc arlequin",
  "black tortie silver spotted tabby & blanc bicolore",
  "black tortie silver tabby",
  "black tortie silver tabby & blanc",
  "black tortie silver tabby & blanc arlequin",
  "black tortie silver tabby & blanc van",
  "black tortie silver ticked tabby",
  "black tortie silver ticked tabby & blanc",
  "black tortie smoke",
  "black tortie smoke & blanc",
  "black tortie smoke & blanc arlequin",
  "black tortie smoke & blanc bicolore",
  "black tortie smoke & blanc van",
  "blanc",
  "bleu",
  "bleu & blanc",
  "bleu & blanc arlequin",
  "bleu & blanc bicolore",
  "bleu & blanc van",
  "bleu ambre",
  "bleu ambre & blanc",
  "blue amber blotched tabby",
  "blue amber blotched tabby & blanc",
  "blue amber mackerel tabby",
  "blue amber mackerel tabby & blanc",
  "blue amber silver blotched tabby",
  "blue amber silver blotched tabby & blanc",
  "blue amber silver mackerel tabby",
  "blue amber silver mackerel tabby & blanc",
  "blue amber silver shaded",
  "blue amber silver spotted tabby",
  "blue amber smoke",
  "blue amber smoke & blanc",
  "blue amber spotted tabby",
  "blue amber spotted tabby & blanc",
  "blue amber ticked tabby & blanc",
  "blue blotched tabby",
  "blue blotched tabby & blanc",
  "blue blotched tabby & blanc arlequin",
  "blue blotched tabby & blanc bicolore",
  "blue blotched tabby mink",
  "blue blotched tabby mink & blanc",
  "blue blotched tabby mink & blanc bicolore",
  "blue blotched tabby mink mitted",
  "blue chinchilla",
  "blue chinchilla point",
  "blue golden shaded",
  "blue golden shaded & blanc",
  "blue golden shaded point",
  "blue golden shaded sepia",
  "blue golden shaded yx or",
  "blue golden shell",
  "blue golden shell & blanc",
  "blue golden shell point",
  "blue mackerel tabby",
  "blue mackerel tabby & blanc",
  "blue mackerel tabby & blanc arlequin",
  "blue mackerel tabby & blanc bicolore",
  "blue mackerel tabby mink",
  "blue mackerel tabby mink & blanc",
  "blue mackerel tabby mink & blanc arlequin",
  "blue mackerel tabby sepia",
  "blue mackerel tabby sepia & blanc",
  "blue mink",
  "blue mink & blanc",
  "blue mink & blanc arlequin",
  "blue mink & blanc bicolore",
  "blue mink & blanc van",
  "blue mink mitted",
  "blue point",
  "blue point & blanc",
  "blue point & blanc arlequin",
  "blue point & blanc bicolore",
  "blue point & blanc van",
  "blue point mitted",
  "blue sepia",
  "blue sepia & blanc",
  "blue sepia mitted",
  "blue silver blotched tabby",
  "blue silver blotched tabby & blanc",
  "blue silver blotched tabby & blanc arlequin",
  "blue silver blotched tabby & blanc bicolore",
  "blue silver blotched tabby mink",
  "blue silver mackerel tabby",
  "blue silver mackerel tabby & blanc",
  "blue silver mackerel tabby & blanc arlequin",
  "blue silver mackerel tabby mink",
  "blue silver mackerel tabby sepia",
  "blue silver shaded",
  "blue silver shaded & blanc",
  "blue silver shaded & blanc arlequin",
  "blue silver shaded point",
  "blue silver shaded point & blanc",
  "blue silver shaded sepia",
  "blue silver shaded yx or",
  "blue silver spotted tabby",
  "blue silver spotted tabby & blanc",
  "blue silver spotted tabby & blanc arlequin",
  "blue silver spotted tabby & blanc bicolore",
  "blue silver spotted tabby mink",
  "blue silver spotted tabby mink & blanc",
  "blue silver tabby",
  "blue silver tabby (motif spotted/rosettes)",
  "blue silver tabby & blanc",
  "blue silver tabby & blanc arlequin",
  "blue silver tabby & blanc van",
  "blue silver tabby point",
  "blue silver tabby point & blanc",
  "blue silver tabby point & blanc bicolore",
  "blue silver tabby point mitted",
  "blue silver ticked tabby",
  "blue silver ticked tabby & blanc",
  "blue silver ticked tabby & blanc bicolore",
  "blue silver ticked tabby mink",
  "blue silver ticked tabby sepia",
  "blue smoke",
  "blue smoke & blanc",
  "blue smoke & blanc arlequin",
  "blue smoke & blanc bicolore",
  "blue smoke & blanc van",
  "blue smoke mink",
  "blue smoke mink & blanc bicolore",
  "blue smoke point",
  "blue smoke point & blanc",
  "blue smoke sepia",
  "blue spotted tabby",
  "blue spotted tabby & blanc",
  "blue spotted tabby & blanc arlequin",
  "blue spotted tabby & blanc bicolore",
  "blue spotted tabby mink",
  "blue spotted tabby mink & blanc",
  "blue spotted tabby mink & blanc bicolore",
  "blue tabby",
  "blue tabby (motif marble)",
  "blue tabby (motif spotted/rosettes)",
  "blue tabby & blanc",
  "blue tabby & blanc arlequin",
  "blue tabby & blanc bicolore",
  "blue tabby & blanc van",
  "blue tabby mink",
  "blue tabby mink (motif marble)",
  "blue tabby mink (motif spotted/rosettes)",
  "blue tabby mink & blanc",
  "blue tabby mink & blanc bicolore",
  "blue tabby point",
  "blue tabby point (motif spotted/rosettes)",
  "blue tabby point & blanc",
  "blue tabby point & blanc arlequin",
  "blue tabby point & blanc bicolore",
  "blue tabby point mitted",
  "blue tabby sepia",
  "blue tabby sepia (motif spotted/rosettes)",
  "blue ticked tabby",
  "blue ticked tabby & blanc",
  "blue ticked tabby & blanc arlequin",
  "blue ticked tabby & blanc bicolore",
  "blue ticked tabby mink",
  "blue tortie",
  "blue tortie & blanc",
  "blue tortie & blanc arlequin",
  "blue tortie & blanc bicolore",
  "blue tortie & blanc van",
  "blue tortie amber blotched tabby",
  "blue tortie amber blotched tabby & blanc",
  "blue tortie amber blotched tabby & blanc bicolore",
  "blue tortie amber silver mackerel tabby",
  "blue tortie amber silver tabby",
  "blue tortie amber silver ticked tabby & blanc",
  "blue tortie amber smoke",
  "blue tortie amber spotted tabby & blanc",
  "blue tortie blotched tabby",
  "blue tortie blotched tabby & blanc",
  "blue tortie blotched tabby & blanc arlequin",
  "blue tortie blotched tabby & blanc bicolore",
  "blue tortie blotched tabby mink",
  "blue tortie blotched tabby mink & blanc",
  "blue tortie blotched tabby mitted",
  "blue tortie chinchilla",
  "blue tortie chinchilla point",
  "blue tortie golden shaded",
  "blue tortie golden shaded point",
  "blue tortie golden shaded sepia",
  "blue tortie golden shaded yx or",
  "blue tortie golden shell",
  "blue tortie golden shell & blanc arlequin",
  "blue tortie mackerel tabby",
  "blue tortie mackerel tabby & blanc",
  "blue tortie mackerel tabby & blanc arlequin",
  "blue tortie mackerel tabby & blanc bicolore",
  "blue tortie mackerel tabby mink",
  "blue tortie mackerel tabby mink & blanc",
  "blue tortie mink",
  "blue tortie mink & blanc",
  "blue tortie mink & blanc arlequin",
  "blue tortie mink & blanc bicolore",
  "blue tortie mink mitted",
  "blue tortie mitted",
  "blue tortie point",
  "blue tortie point & blanc",
  "blue tortie point & blanc arlequin",
  "blue tortie point & blanc bicolore",
  "blue tortie point mitted",
  "blue tortie sepia",
  "blue tortie sepia & blanc",
  "blue tortie silver blotched tabby",
  "blue tortie silver blotched tabby & blanc",
  "blue tortie silver blotched tabby & blanc arlequin",
  "blue tortie silver blotched tabby & blanc bicolore",
  "blue tortie silver mackerel tabby",
  "blue tortie silver mackerel tabby & blanc",
  "blue tortie silver mackerel tabby & blanc arlequin",
  "blue tortie silver mackerel tabby & blanc bicolore",
  "blue tortie silver shaded",
  "blue tortie silver shaded & blanc",
  "blue tortie silver shaded point",
  "blue tortie silver shaded yx or",
  "blue tortie silver spotted tabby",
  "blue tortie silver spotted tabby & blanc",
  "blue tortie silver spotted tabby & blanc bicolore",
  "blue tortie silver tabby",
  "blue tortie silver tabby & blanc",
  "blue tortie silver tabby & blanc arlequin",
  "blue tortie silver tabby & blanc van",
  "blue tortie silver tabby point",
  "blue tortie silver tabby point & blanc",
  "blue tortie silver tabby point mitted",
  "blue tortie silver ticked tabby",
  "blue tortie silver ticked tabby & blanc",
  "blue tortie smoke",
  "blue tortie smoke & blanc",
  "blue tortie smoke & blanc arlequin",
  "blue tortie smoke & blanc bicolore",
  "blue tortie smoke & blanc van",
  "blue tortie smoke mink",
  "blue tortie smoke point",
  "blue tortie smoke point & blanc",
  "blue tortie smoke point mitted",
  "blue tortie spotted tabby",
  "blue tortie spotted tabby & blanc",
  "blue tortie spotted tabby & blanc arlequin",
  "blue tortie spotted tabby & blanc bicolore",
  "blue tortie spotted tabby mink & blanc",
  "blue tortie spotted tabby sepia",
  "blue tortie tabby",
  "blue tortie tabby & blanc",
  "blue tortie tabby & blanc arlequin",
  "blue tortie tabby & blanc bicolore",
  "blue tortie tabby & blanc van",
  "blue tortie tabby mink",
  "blue tortie tabby mink & blanc",
  "blue tortie tabby mink mitted",
  "blue tortie tabby point",
  "blue tortie tabby point & blanc",
  "blue tortie tabby point & blanc arlequin",
  "blue tortie tabby point & blanc bicolore",
  "blue tortie tabby point mitted",
  "blue tortie ticked tabby",
  "blue tortie ticked tabby & blanc",
  "brown amber blotched tabby",
  "brown amber blotched tabby & blanc",
  "brown amber blotched tabby & blanc arlequin",
  "brown amber mackerel tabby",
  "brown amber mackerel tabby & blanc",
  "brown amber spotted tabby",
  "brown amber spotted tabby & blanc",
  "brown amber tabby & blanc",
  "brown amber ticked tabby",
  "brown amber ticked tabby & blanc",
  "brown blotched tabby",
  "brown blotched tabby & blanc",
  "brown blotched tabby & blanc arlequin",
  "brown blotched tabby & blanc bicolore",
  "brown mackerel tabby",
  "brown mackerel tabby & blanc",
  "brown mackerel tabby & blanc arlequin",
  "brown mackerel tabby & blanc bicolore",
  "brown spotted tabby",
  "brown spotted tabby (bronze)",
  "brown spotted tabby & blanc",
  "brown spotted tabby & blanc arlequin",
  "brown spotted tabby & blanc bicolore",
  "brown tabby",
  "brown tabby (motif marble)",
  "brown tabby (motif spotted/rosettes)",
  "brown tabby & blanc",
  "brown tabby & blanc arlequin",
  "brown tabby & blanc bicolore",
  "brown tabby & blanc van",
  "brown ticked tabby",
  "brown ticked tabby (lièvre)",
  "brown ticked tabby & blanc",
  "brown ticked tabby & blanc arlequin",
  "brown ticked tabby & blanc bicolore",
  "brown tortie amber blotched tabby & blanc",
  "brown tortie amber mackerel tabby",
  "brown tortie amber mackerel tabby & blanc",
  "brown tortie amber spotted tabby & blanc",
  "brown tortie blotched tabby",
  "brown tortie blotched tabby & blanc",
  "brown tortie blotched tabby & blanc arlequin",
  "brown tortie blotched tabby & blanc bicolore",
  "brown tortie mackerel tabby",
  "brown tortie mackerel tabby & blanc",
  "brown tortie mackerel tabby & blanc arlequin",
  "brown tortie mackerel tabby & blanc bicolore",
  "brown tortie spotted tabby",
  "brown tortie spotted tabby & blanc",
  "brown tortie spotted tabby & blanc arlequin",
  "brown tortie spotted tabby & blanc bicolore",
  "brown tortie tabby",
  "brown tortie tabby & blanc",
  "brown tortie tabby & blanc arlequin",
  "brown tortie tabby & blanc bicolore",
  "brown tortie tabby & blanc van",
  "brown tortie ticked tabby",
  "brown tortie ticked tabby (lièvre tortie)",
  "brown tortie ticked tabby & blanc",
  "brown tortie ticked tabby & blanc bicolore",
  "chocolat",
  "chocolat & blanc",
  "chocolat & blanc arlequin",
  "chocolat & blanc bicolore",
  "chocolat & blanc van",
  "chocolat blotched tabby",
  "chocolat blotched tabby & blanc",
  "chocolat blotched tabby & blanc arlequin",
  "chocolat blotched tabby & blanc bicolore",
  "chocolat blotched tabby mink",
  "chocolat blotched tabby mink & blanc",
  "chocolat chinchilla",
  "chocolat chinchilla point",
  "chocolat golden shaded",
  "chocolat golden shaded & blanc",
  "chocolat golden shaded point",
  "chocolat golden shaded point & blanc arlequin",
  "chocolat golden shaded sepia",
  "chocolat golden shell",
  "chocolat mackerel tabby",
  "chocolat mackerel tabby & blanc",
  "chocolat mackerel tabby & blanc arlequin",
  "chocolat mackerel tabby & blanc bicolore",
  "chocolat mackerel tabby mink",
  "chocolat mackerel tabby mink & blanc",
  "chocolat mackerel tabby mink & blanc arlequin",
  "chocolat mackerel tabby sepia",
  "chocolat mackerel tabby sepia & blanc",
  "chocolat mink",
  "chocolat mink & blanc",
  "chocolat mink & blanc arlequin",
  "chocolat mink & blanc bicolore",
  "chocolat mink & blanc van",
  "chocolat mink mitted",
  "chocolat point",
  "chocolat point & blanc",
  "chocolat point & blanc arlequin",
  "chocolat point & blanc bicolore",
  "chocolat point & blanc van",
  "chocolat point mitted",
  "chocolat sepia",
  "chocolat sepia & blanc",
  "chocolat sepia & blanc bicolore",
  "chocolat sepia & blanc van",
  "chocolat silver blotched tabby",
  "chocolat silver blotched tabby & blanc",
  "chocolat silver blotched tabby & blanc arlequin",
  "chocolat silver blotched tabby & blanc bicolore",
  "chocolat silver mackerel tabby",
  "chocolat silver mackerel tabby & blanc",
  "chocolat silver mackerel tabby & blanc arlequin",
  "chocolat silver mackerel tabby mink",
  "chocolat silver mackerel tabby mink & blanc",
  "chocolat silver mackerel tabby mink & blanc arlequin",
  "chocolat silver shaded",
  "chocolat silver shaded & blanc",
  "chocolat silver shaded point",
  "chocolat silver shaded sepia",
  "chocolat silver shaded yx or",
  "chocolat silver spotted tabby",
  "chocolat silver spotted tabby & blanc",
  "chocolat silver spotted tabby & blanc arlequin",
  "chocolat silver spotted tabby & blanc bicolore",
  "chocolat silver spotted tabby mink",
  "chocolat silver tabby",
  "chocolat silver tabby & blanc",
  "chocolat silver tabby & blanc van",
  "chocolat silver tabby mink",
  "chocolat silver tabby point",
  "chocolat silver tabby point & blanc",
  "chocolat silver tabby point mitted",
  "chocolat silver ticked tabby",
  "chocolat silver ticked tabby & blanc",
  "chocolat silver ticked tabby mink",
  "chocolat silver ticked tabby sepia",
  "chocolat smoke",
  "chocolat smoke & blanc",
  "chocolat smoke & blanc arlequin",
  "chocolat smoke & blanc bicolore",
  "chocolat smoke mink",
  "chocolat smoke mink & blanc",
  "chocolat smoke point",
  "chocolat smoke point & blanc",
  "chocolat smoke sepia",
  "chocolat spotted tabby",
  "chocolat spotted tabby & blanc",
  "chocolat spotted tabby & blanc arlequin",
  "chocolat spotted tabby & blanc bicolore",
  "chocolat spotted tabby mink",
  "chocolat spotted tabby sepia",
  "chocolat tabby",
  "chocolat tabby & blanc",
  "chocolat tabby & blanc arlequin",
  "chocolat tabby & blanc van",
  "chocolat tabby mink",
  "chocolat tabby mink & blanc",
  "chocolat tabby mink & blanc arlequin",
  "chocolat tabby mink & blanc bicolore",
  "chocolat tabby point",
  "chocolat tabby point & blanc",
  "chocolat tabby point & blanc bicolore",
  "chocolat tabby point mitted",
  "chocolat ticked tabby",
  "chocolat ticked tabby & blanc",
  "chocolat ticked tabby & blanc bicolore",
  "chocolat ticked tabby sepia",
  "chocolat tortie",
  "chocolat tortie & blanc",
  "chocolat tortie & blanc arlequin",
  "chocolat tortie & blanc bicolore",
  "chocolat tortie & blanc van",
  "chocolat tortie blotched tabby",
  "chocolat tortie blotched tabby & blanc",
  "chocolat tortie blotched tabby & blanc bicolore",
  "chocolat tortie golden shaded point",
  "chocolat tortie golden shell",
  "chocolat tortie mackerel tabby",
  "chocolat tortie mackerel tabby & blanc",
  "chocolat tortie mackerel tabby & blanc arlequin",
  "chocolat tortie mackerel tabby mink",
  "chocolat tortie mackerel tabby mink & blanc",
  "chocolat tortie mackerel tabby sepia & blanc",
  "chocolat tortie mink",
  "chocolat tortie mink & blanc",
  "chocolat tortie mink & blanc arlequin",
  "chocolat tortie mink & blanc bicolore",
  "chocolat tortie point",
  "chocolat tortie point & blanc",
  "chocolat tortie point & blanc arlequin",
  "chocolat tortie point & blanc bicolore",
  "chocolat tortie point mitted",
  "chocolat tortie sepia",
  "chocolat tortie sepia & blanc",
  "chocolat tortie silver blotched tabby",
  "chocolat tortie silver blotched tabby & blanc",
  "chocolat tortie silver blotched tabby & blanc arlequin",
  "chocolat tortie silver blotched tabby & blanc bicolore",
  "chocolat tortie silver blotched tabby mink",
  "chocolat tortie silver mackerel tabby",
  "chocolat tortie silver mackerel tabby & blanc",
  "chocolat tortie silver shaded",
  "chocolat tortie silver shaded point",
  "chocolat tortie silver shaded sepia",
  "chocolat tortie silver spotted tabby",
  "chocolat tortie silver spotted tabby & blanc",
  "chocolat tortie silver spotted tabby & blanc arlequin",
  "chocolat tortie silver spotted tabby & blanc bicolore",
  "chocolat tortie silver tabby mink",
  "chocolat tortie silver tabby mink & blanc",
  "chocolat tortie silver tabby point",
  "chocolat tortie silver tabby point & blanc",
  "chocolat tortie silver ticked tabby",
  "chocolat tortie silver ticked tabby mink",
  "chocolat tortie smoke",
  "chocolat tortie smoke & blanc",
  "chocolat tortie smoke & blanc bicolore",
  "chocolat tortie smoke mink",
  "chocolat tortie smoke mink & blanc",
  "chocolat tortie smoke point",
  "chocolat tortie smoke point & blanc",
  "chocolat tortie smoke sepia",
  "chocolat tortie spotted tabby",
  "chocolat tortie spotted tabby & blanc",
  "chocolat tortie spotted tabby & blanc bicolore",
  "chocolat tortie spotted tabby mink",
  "chocolat tortie tabby",
  "chocolat tortie tabby mink",
  "chocolat tortie tabby mink & blanc",
  "chocolat tortie tabby point",
  "chocolat tortie tabby point & blanc",
  "chocolat tortie tabby point & blanc arlequin",
  "chocolat tortie tabby point & blanc bicolore",
  "chocolat tortie tabby point mitted",
  "chocolat tortie ticked tabby",
  "chocolat tortie ticked tabby & blanc",
  "chocolat tortie ticked tabby mink",
  "cinnamon",
  "cinnamon & blanc",
  "cinnamon & blanc arlequin",
  "cinnamon & blanc bicolore",
  "cinnamon & blanc van",
  "cinnamon blotched tabby",
  "cinnamon blotched tabby & blanc",
  "cinnamon blotched tabby & blanc bicolore",
  "cinnamon golden shaded",
  "cinnamon mackerel tabby",
  "cinnamon mackerel tabby & blanc",
  "cinnamon mackerel tabby & blanc arlequin",
  "cinnamon mackerel tabby & blanc bicolore",
  "cinnamon mink",
  "cinnamon mink & blanc",
  "cinnamon mink & blanc arlequin",
  "cinnamon point",
  "cinnamon point & blanc",
  "cinnamon point & blanc bicolore",
  "cinnamon point mitted",
  "cinnamon sepia",
  "cinnamon silver blotched tabby",
  "cinnamon silver blotched tabby & blanc",
  "cinnamon silver mackerel tabby",
  "cinnamon silver mackerel tabby & blanc",
  "cinnamon silver spotted tabby",
  "cinnamon silver spotted tabby & blanc",
  "cinnamon silver tabby & blanc",
  "cinnamon silver tabby point",
  "cinnamon silver ticked tabby",
  "cinnamon smoke",
  "cinnamon smoke & blanc",
  "cinnamon smoke point",
  "cinnamon spotted tabby",
  "cinnamon spotted tabby & blanc",
  "cinnamon spotted tabby & blanc bicolore",
  "cinnamon spotted tabby sepia & blanc bicolore",
  "cinnamon tabby",
  "cinnamon tabby & blanc",
  "cinnamon tabby & blanc arlequin",
  "cinnamon tabby & blanc van",
  "cinnamon tabby mink",
  "cinnamon tabby mink & blanc",
  "cinnamon tabby point",
  "cinnamon tabby sepia",
  "cinnamon ticked tabby",
  "cinnamon ticked tabby (sorrel)",
  "cinnamon ticked tabby & blanc",
  "cinnamon ticked tabby & blanc arlequin",
  "cinnamon ticked tabby & blanc bicolore",
  "cinnamon tortie",
  "cinnamon tortie & blanc",
  "cinnamon tortie & blanc arlequin",
  "cinnamon tortie & blanc bicolore",
  "cinnamon tortie & blanc van",
  "cinnamon tortie blotched tabby",
  "cinnamon tortie blotched tabby & blanc",
  "cinnamon tortie mackerel tabby",
  "cinnamon tortie mackerel tabby & blanc",
  "cinnamon tortie mackerel tabby mitted",
  "cinnamon tortie point",
  "cinnamon tortie point & blanc",
  "cinnamon tortie silver tabby point",
  "cinnamon tortie silver ticked tabby",
  "cinnamon tortie smoke",
  "cinnamon tortie smoke & blanc",
  "cinnamon tortie smoke & blanc arlequin",
  "cinnamon tortie smoke point & blanc",
  "cinnamon tortie spotted tabby",
  "cinnamon tortie spotted tabby & blanc",
  "cinnamon tortie spotted tabby & blanc arlequin",
  "cinnamon tortie tabby & blanc",
  "cinnamon tortie tabby point",
  "cinnamon tortie ticked tabby (sorrel tortie)",
  "crème",
  "crème & blanc",
  "crème & blanc arlequin",
  "crème & blanc van",
  "crème blotched tabby",
  "crème blotched tabby & blanc",
  "crème blotched tabby & blanc arlequin",
  "crème blotched tabby mink",
  "crème chinchilla",
  "crème chinchilla & blanc",
  "crème chinchilla & blanc yx or",
  "crème chinchilla point",
  "crème chinchilla yx or",
  "crème golden shaded",
  "crème golden shaded yx or",
  "crème mackerel tabby",
  "crème mackerel tabby & blanc",
  "crème mackerel tabby & blanc arlequin",
  "crème mackerel tabby mink",
  "crème mink",
  "crème mink & blanc",
  "crème mink & blanc arlequin",
  "crème mink & blanc van",
  "crème point",
  "crème point & blanc",
  "crème point mitted",
  "crème sepia",
  "crème sepia & blanc",
  "crème silver blotched tabby",
  "crème silver blotched tabby & blanc",
  "crème silver blotched tabby & blanc arlequin",
  "crème silver blotched tabby mink & blanc",
  "crème silver mackerel tabby",
  "crème silver mackerel tabby & blanc",
  "crème silver shaded",
  "crème silver shaded & blanc",
  "crème silver shaded & blanc yx or",
  "crème silver shaded point",
  "crème silver shaded yx or",
  "crème silver spotted tabby",
  "crème silver spotted tabby & blanc",
  "crème silver tabby",
  "crème silver tabby & blanc",
  "crème silver tabby & blanc van",
  "crème silver tabby point",
  "crème silver tabby point & blanc",
  "crème silver ticked tabby",
  "crème silver ticked tabby & blanc",
  "crème silver ticked tabby mink",
  "crème silver ticked tabby mink & blanc",
  "crème smoke",
  "crème smoke & blanc",
  "crème smoke & blanc arlequin",
  "crème smoke & blanc van",
  "crème smoke mink",
  "crème smoke mink & blanc",
  "crème smoke point",
  "crème smoke point & blanc",
  "crème spotted tabby",
  "crème spotted tabby & blanc",
  "crème tabby",
  "crème tabby & blanc",
  "crème tabby & blanc van",
  "crème tabby mink",
  "crème tabby mink & blanc",
  "crème tabby point",
  "crème tabby point & blanc",
  "crème tabby point mitted",
  "crème ticked tabby",
  "crème ticked tabby & blanc",
  "fawn",
  "fawn & blanc",
  "fawn & blanc arlequin",
  "fawn & blanc bicolore",
  "fawn & blanc van",
  "fawn blotched tabby",
  "fawn blotched tabby & blanc",
  "fawn chinchilla",
  "fawn golden shaded",
  "fawn golden shaded point",
  "fawn mackerel tabby",
  "fawn mackerel tabby & blanc",
  "fawn mink",
  "fawn point",
  "fawn point & blanc",
  "fawn point & blanc bicolore",
  "fawn sepia",
  "fawn silver blotched tabby",
  "fawn silver blotched tabby & blanc",
  "fawn silver blotched tabby & blanc arlequin",
  "fawn silver mackerel tabby",
  "fawn silver mackerel tabby & blanc",
  "fawn silver shaded",
  "fawn silver spotted tabby",
  "fawn silver spotted tabby & blanc",
  "fawn silver spotted tabby mink",
  "fawn silver tabby",
  "fawn silver tabby & blanc van",
  "fawn silver tabby point",
  "fawn silver ticked tabby",
  "fawn smoke",
  "fawn smoke & blanc",
  "fawn smoke point",
  "fawn smoke point & blanc",
  "fawn spotted tabby",
  "fawn spotted tabby & blanc",
  "fawn tabby",
  "fawn tabby & blanc",
  "fawn tabby & blanc bicolore",
  "fawn tabby point",
  "fawn tabby point & blanc",
  "fawn ticked tabby",
  "fawn ticked tabby & blanc",
  "fawn ticked tabby mink",
  "fawn tortie",
  "fawn tortie & blanc",
  "fawn tortie & blanc arlequin",
  "fawn tortie & blanc bicolore",
  "fawn tortie & blanc van",
  "fawn tortie blotched tabby",
  "fawn tortie mackerel tabby",
  "fawn tortie mink",
  "fawn tortie point",
  "fawn tortie point & blanc",
  "fawn tortie point & blanc bicolore",
  "fawn tortie sepia",
  "fawn tortie silver blotched tabby",
  "fawn tortie silver spotted tabby & blanc",
  "fawn tortie smoke",
  "fawn tortie smoke & blanc",
  "fawn tortie spotted tabby",
  "fawn tortie tabby",
  "fawn tortie tabby point",
  "fawn tortie ticked tabby",
  "lilac blotched tabby",
  "lilac blotched tabby & blanc",
  "lilac blotched tabby & blanc bicolore",
  "lilac blotched tabby mink",
  "lilac blotched tabby mink & blanc",
  "lilac blotched tabby sepia & blanc",
  "lilac chinchilla",
  "lilac chinchilla point",
  "lilac golden shaded",
  "lilac golden shaded & blanc",
  "lilac golden shaded point",
  "lilac golden shaded sepia",
  "lilac golden shell",
  "lilac golden shell point",
  "lilac mackerel tabby",
  "lilac mackerel tabby & blanc",
  "lilac mackerel tabby & blanc arlequin",
  "lilac mackerel tabby mink",
  "lilac mackerel tabby mink & blanc",
  "lilac mink",
  "lilac mink & blanc",
  "lilac mink & blanc arlequin",
  "lilac mink & blanc bicolore",
  "lilac point",
  "lilac point & blanc",
  "lilac point & blanc bicolore",
  "lilac point mitted",
  "lilac sepia",
  "lilac sepia & blanc",
  "lilac sepia & blanc van",
  "lilac silver blotched tabby",
  "lilac silver blotched tabby & blanc",
  "lilac silver mackerel tabby",
  "lilac silver mackerel tabby & blanc",
  "lilac silver shaded",
  "lilac silver shaded point",
  "lilac silver shaded sepia",
  "lilac silver spotted tabby",
  "lilac silver spotted tabby & blanc",
  "lilac silver spotted tabby mink",
  "lilac silver tabby",
  "lilac silver tabby point",
  "lilac silver tabby point & blanc",
  "lilac silver tabby point mitted",
  "lilac silver ticked tabby",
  "lilac silver ticked tabby mink",
  "lilac smoke",
  "lilac smoke & blanc",
  "lilac smoke mink",
  "lilac smoke point",
  "lilac smoke point & blanc",
  "lilac spotted tabby",
  "lilac spotted tabby & blanc",
  "lilac spotted tabby & blanc arlequin",
  "lilac spotted tabby & blanc bicolore",
  "lilac spotted tabby mink",
  "lilac tabby",
  "lilac tabby & blanc",
  "lilac tabby & blanc van",
  "lilac tabby mink",
  "lilac tabby mink & blanc",
  "lilac tabby point",
  "lilac tabby point & blanc",
  "lilac tabby point & blanc arlequin",
  "lilac tabby point & blanc bicolore",
  "lilac tabby point & blanc van",
  "lilac tabby point mitted",
  "lilac ticked tabby",
  "lilac ticked tabby & blanc",
  "lilac ticked tabby mink",
  "lilac ticked tabby sepia",
  "lilac tortie",
  "lilac tortie & blanc",
  "lilac tortie & blanc arlequin",
  "lilac tortie & blanc bicolore",
  "lilac tortie & blanc van",
  "lilac tortie blotched tabby",
  "lilac tortie blotched tabby & blanc",
  "lilac tortie blotched tabby & blanc bicolore",
  "lilac tortie chinchilla point",
  "lilac tortie mackerel tabby",
  "lilac tortie mackerel tabby & blanc",
  "lilac tortie mackerel tabby & blanc arlequin",
  "lilac tortie mackerel tabby mink & blanc",
  "lilac tortie mink",
  "lilac tortie mink & blanc",
  "lilac tortie point",
  "lilac tortie point & blanc",
  "lilac tortie point & blanc arlequin",
  "lilac tortie point & blanc bicolore",
  "lilac tortie point mitted",
  "lilac tortie sepia",
  "lilac tortie silver blotched tabby",
  "lilac tortie silver mackerel tabby",
  "lilac tortie silver shaded",
  "lilac tortie silver shaded point",
  "lilac tortie silver spotted tabby",
  "lilac tortie silver tabby & blanc van",
  "lilac tortie silver tabby point",
  "lilac tortie silver ticked tabby",
  "lilac tortie silver ticked tabby & blanc",
  "lilac tortie silver ticked tabby mink",
  "lilac tortie silver ticked tabby sepia",
  "lilac tortie smoke",
  "lilac tortie smoke & blanc",
  "lilac tortie smoke & blanc bicolore",
  "lilac tortie smoke point",
  "lilac tortie smoke point & blanc",
  "lilac tortie spotted tabby",
  "lilac tortie spotted tabby & blanc",
  "lilac tortie spotted tabby & blanc bicolore",
  "lilac tortie tabby",
  "lilac tortie tabby & blanc van",
  "lilac tortie tabby mink",
  "lilac tortie tabby mink & blanc",
  "lilac tortie tabby point",
  "lilac tortie tabby point & blanc",
  "lilac tortie tabby point mitted",
  "lilac tortie ticked tabby",
  "lilac tortie ticked tabby & blanc",
  "lilac tortie ticked tabby & blanc bicolore",
  "lilac tortie ticked tabby sepia",
  "lilas",
  "lilas & blanc",
  "lilas & blanc arlequin",
  "lilas & blanc bicolore",
  "lilas & blanc van",
  "noir",
  "noir & blanc",
  "noir & blanc arlequin",
  "noir & blanc bicolore",
  "noir & blanc van",
  "noir ambre",
  "noir ambre & blanc",
  "noir mitted",
  "red blotched tabby",
  "red blotched tabby & blanc",
  "red blotched tabby & blanc arlequin",
  "red blotched tabby & blanc bicolore",
  "red blotched tabby mink & blanc",
  "red chinchilla",
  "red chinchilla & blanc",
  "red chinchilla & blanc yx or",
  "red chinchilla point",
  "red chinchilla yx or",
  "red golden shaded",
  "red golden shaded & blanc",
  "red golden shaded point",
  "red golden shell",
  "red golden shell & blanc",
  "red mackerel tabby",
  "red mackerel tabby & blanc",
  "red mackerel tabby & blanc arlequin",
  "red mackerel tabby & blanc bicolore",
  "red mackerel tabby mink",
  "red mackerel tabby mink & blanc",
  "red mackerel tabby mink & blanc arlequin",
  "red mackerel tabby sepia",
  "red mackerel tabby sepia & blanc",
  "red mink",
  "red mink & blanc",
  "red mink & blanc arlequin",
  "red mink & blanc bicolore",
  "red mink & blanc van",
  "red mink mitted",
  "red point",
  "red point & blanc",
  "red point & blanc arlequin",
  "red point & blanc bicolore",
  "red point & blanc van",
  "red point mitted",
  "red sepia",
  "red sepia & blanc",
  "red silver blotched tabby",
  "red silver blotched tabby & blanc",
  "red silver blotched tabby & blanc arlequin",
  "red silver blotched tabby & blanc bicolore",
  "red silver blotched tabby mink",
  "red silver mackerel tabby",
  "red silver mackerel tabby & blanc",
  "red silver mackerel tabby & blanc arlequin",
  "red silver mackerel tabby & blanc bicolore",
  "red silver mackerel tabby mink & blanc",
  "red silver shaded",
  "red silver shaded & blanc",
  "red silver shaded & blanc arlequin yx or",
  "red silver shaded & blanc van",
  "red silver shaded & blanc yx or",
  "red silver shaded point",
  "red silver shaded point & blanc",
  "red silver shaded sepia",
  "red silver shaded yx or",
  "red silver spotted tabby",
  "red silver spotted tabby & blanc",
  "red silver spotted tabby & blanc arlequin",
  "red silver spotted tabby & blanc bicolore",
  "red silver tabby",
  "red silver tabby & blanc",
  "red silver tabby & blanc arlequin",
  "red silver tabby & blanc van",
  "red silver tabby mink & blanc",
  "red silver tabby point",
  "red silver tabby point & blanc",
  "red silver ticked tabby",
  "red silver ticked tabby & blanc",
  "red silver ticked tabby & blanc bicolore",
  "red silver ticked tabby sepia",
  "red smoke",
  "red smoke & blanc",
  "red smoke & blanc arlequin",
  "red smoke & blanc bicolore",
  "red smoke & blanc van",
  "red smoke mink",
  "red smoke point",
  "red smoke point & blanc",
  "red spotted tabby",
  "red spotted tabby & blanc",
  "red spotted tabby & blanc arlequin",
  "red spotted tabby & blanc bicolore",
  "red tabby",
  "red tabby & blanc",
  "red tabby & blanc arlequin",
  "red tabby & blanc bicolore",
  "red tabby & blanc van",
  "red tabby mink & blanc",
  "red tabby point",
  "red tabby point & blanc",
  "red tabby point & blanc bicolore",
  "red tabby point mitted",
  "red tabby sepia",
  "red tabby sepia & blanc",
  "red ticked tabby",
  "red ticked tabby & blanc",
  "red ticked tabby & blanc arlequin",
  "red ticked tabby & blanc bicolore",
  "red ticked tabby mink",
  "roux",
  "roux & blanc",
  "roux & blanc arlequin",
  "roux & blanc bicolore",
  "roux & blanc van",
  "seal blotched tabby mink",
  "seal blotched tabby mink & blanc",
  "seal blotched tabby mink & blanc bicolore",
  "seal blotched tabby sepia",
  "seal blotched tabby sepia & blanc",
  "seal chinchilla mink",
  "seal chinchilla point",
  "seal chinchilla point & blanc",
  "seal chinchilla sepia",
  "seal golden shaded point",
  "seal golden shaded point & blanc",
  "seal golden shaded point & blanc bicolore",
  "seal golden shaded sepia",
  "seal golden shell mink",
  "seal golden shell point",
  "seal golden shell sepia",
  "seal mackerel tabby mink",
  "seal mackerel tabby mink & blanc",
  "seal mackerel tabby mink & blanc arlequin",
  "seal mackerel tabby mink & blanc bicolore",
  "seal mackerel tabby sepia",
  "seal mackerel tabby sepia & blanc",
  "seal mackerel tabby sepia & blanc arlequin",
  "seal mink",
  "seal mink & blanc",
  "seal mink & blanc arlequin",
  "seal mink & blanc bicolore",
  "seal mink & blanc van",
  "seal mink mitted",
  "seal point",
  "seal point & blanc",
  "seal point & blanc arlequin",
  "seal point & blanc bicolore",
  "seal point & blanc van",
  "seal point mitted",
  "seal sepia",
  "seal sepia (zibeline)",
  "seal sepia & blanc",
  "seal sepia & blanc arlequin",
  "seal sepia & blanc bicolore",
  "seal sepia mitted",
  "seal silver blotched tabby sepia",
  "seal silver mackerel tabby mink",
  "seal silver mackerel tabby sepia",
  "seal silver shaded mink",
  "seal silver shaded point",
  "seal silver shaded point & blanc",
  "seal silver shaded sepia",
  "seal silver spotted tabby mink",
  "seal silver spotted tabby mink & blanc",
  "seal silver spotted tabby sepia",
  "seal silver tabby mink",
  "seal silver tabby mink (motif marble)",
  "seal silver tabby mink (motif spotted/rosettes)",
  "seal silver tabby mink & blanc",
  "seal silver tabby point",
  "seal silver tabby point (motif marble)",
  "seal silver tabby point (motif spotted/rosettes)",
  "seal silver tabby point & blanc",
  "seal silver tabby point & blanc bicolore",
  "seal silver tabby point mitted",
  "seal silver tabby sepia (motif spotted/rosettes)",
  "seal silver ticked tabby mink",
  "seal silver ticked tabby sepia",
  "seal smoke mink",
  "seal smoke mink & blanc",
  "seal smoke point",
  "seal smoke point & blanc",
  "seal smoke point mitted",
  "seal smoke sepia",
  "seal spotted tabby mink",
  "seal spotted tabby mink & blanc",
  "seal spotted tabby mink & blanc bicolore",
  "seal tabby mink",
  "seal tabby mink (motif marble)",
  "seal tabby mink (motif spotted/rosettes)",
  "seal tabby mink & blanc",
  "seal tabby mink & blanc arlequin",
  "seal tabby mink & blanc bicolore",
  "seal tabby mink & blanc van",
  "seal tabby mink mitted",
  "seal tabby point",
  "seal tabby point (motif marble)",
  "seal tabby point (motif spotted/rosettes)",
  "seal tabby point & blanc",
  "seal tabby point & blanc arlequin",
  "seal tabby point & blanc bicolore",
  "seal tabby point & blanc van",
  "seal tabby point mitted",
  "seal tabby sepia",
  "seal tabby sepia (motif marble)",
  "seal tabby sepia (motif spotted/rosettes)",
  "seal tabby sepia & blanc",
  "seal tabby sepia & blanc van",
  "seal ticked tabby mink & blanc",
  "seal ticked tabby sepia",
  "seal ticked tabby sepia & blanc",
  "seal tortie blotched tabby mink",
  "seal tortie blotched tabby mink & blanc",
  "seal tortie chinchilla point",
  "seal tortie golden shaded point",
  "seal tortie mackerel tabby mink",
  "seal tortie mackerel tabby mink & blanc",
  "seal tortie mackerel tabby sepia",
  "seal tortie mackerel tabby sepia & blanc",
  "seal tortie mackerel tabby sepia & blanc arlequin",
  "seal tortie mink",
  "seal tortie mink & blanc",
  "seal tortie mink & blanc arlequin",
  "seal tortie mink & blanc bicolore",
  "seal tortie mink & blanc van",
  "seal tortie point",
  "seal tortie point & blanc",
  "seal tortie point & blanc arlequin",
  "seal tortie point & blanc bicolore",
  "seal tortie point & blanc van",
  "seal tortie point mitted",
  "seal tortie sepia",
  "seal tortie sepia & blanc",
  "seal tortie silver blotched tabby mink & blanc",
  "seal tortie silver shaded mink",
  "seal tortie silver shaded point",
  "seal tortie silver shaded point & blanc",
  "seal tortie silver shaded sepia",
  "seal tortie silver tabby mink",
  "seal tortie silver tabby point",
  "seal tortie silver tabby point & blanc",
  "seal tortie silver tabby point & blanc bicolore",
  "seal tortie silver tabby point mitted",
  "seal tortie silver ticked tabby mink",
  "seal tortie smoke mink",
  "seal tortie smoke mink & blanc",
  "seal tortie smoke point",
  "seal tortie smoke point & blanc",
  "seal tortie smoke sepia",
  "seal tortie spotted tabby mink",
  "seal tortie tabby mink",
  "seal tortie tabby mink & blanc",
  "seal tortie tabby mink & blanc arlequin",
  "seal tortie tabby point",
  "seal tortie tabby point & blanc",
  "seal tortie tabby point & blanc arlequin",
  "seal tortie tabby point & blanc bicolore",
  "seal tortie tabby point mitted",
  "seal tortie tabby sepia & blanc",
  "seal tortie tabby sepia mitted",
  "seal tortie ticked tabby mink & blanc",
]
